language: node_js
node_js:
  - '0.8'
  - '0.10'
  - 'node'
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
install: npm install
sudo: required
script: ./test/test.js
