language: node_js
node_js:
  - '0.8'
  - '0.10'
  - 'node'
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
before_script: chmod 0777 ./node_modules/.bin/mocha
script: ./test/test.js
sudo: required
